import type { Metadata } from "next";
import {  Roboto } from "next/font/google";
import "./globals.css";
import Sidemenu from "./Components/Sidemenu"
import { Box, Link } from "@mui/material";
import SideMenuBtn from "./Components/SideMenuBtn";
import { MdCopyright } from "react-icons/md";
import { IoMdHeart } from "react-icons/io";
import Setting from "./Components/Setting";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100',  '300', '400', '500',  '700', '900'],
  variable:'--font-roboto',
  display:'swap'
});
export default function RootLayout({ children,}: Readonly<{

  children: React.ReactNode;
}>) {

 
  return (
    <html lang="en">
      
    
    <body className={`roboto ${roboto.className} `}>

    <Box sx={{ display: 'flex', mr:"16",background:"transparent" }}>
        <Sidemenu />   
        {/* <SideMenuBtn/> */}
        <Box component="main" sx={{ flexGrow: 1,  }}>
          
         {children}
         <Box component="footer" className="flex justify-between px-3">
            <div className="px-3 leading-[1.625] flex items-center text-[#7b809a] text-[14px]">
              <span><MdCopyright/></span>2024, made with <span><IoMdHeart/></span> <Link href="" className="text-[#344767] font-semibold no-underline">&nbsp; Creative Tim &nbsp;</Link> for better web.
            </div>
            <div className="px-3">
              <ul className="flex ">
                <li className="px-4">
                  <Link className="no-underline">
                    <span className="text-[14px] text-[#7b809a] no-underline">Create Tim</span>
                  </Link>
                </li>
                <li className="px-4">
                  <Link className="no-underline">
                    <span className="text-[14px] text-[#7b809a] no-underline">About as</span>
                  </Link>
                </li>
                <li className="px-4">
                  <Link className="no-underline">
                    <span className="text-[14px] text-[#7b809a] no-underline">Blog</span>
                  </Link>
                </li>
                <li className="px-4">
                  <Link className="no-underline">
                    <span className="text-[14px] text-[#7b809a] no-underline">Licence</span>
                  </Link>
                </li>
              </ul>

            </div>
         </Box>
         <Setting/>
      </Box>

    </Box>
      </body>
  </html>
  );
}
